sandbox/Dockerfile, sandbox/Makefile, sandbox/package-lock.json, sandbox/package.json
=> [ERSSUP-61464]-[]-[APIM Fix Repository Vulnerabilities]-[DMW]

azure/azure-pr-pipeline.yml
This reverts commit 4bfa88fc27827f9dc96755ba053c81d487a03862.
=> Revert "[ERSSUP-61464]-[RR]-[APIM Fix Repository Vulnerabilities]-[DMW]"

proxies/live/apiproxy/targets/target.xml, sandbox/package.json
=> ERSSUP-61733 & ERSSUP-61797 - Fix base path for FT env and fix sandbox environment 

proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
=> [ERSSUP-61797]-[JH]-[Fix status endpoint for ft environments]-[RR]

proxies/live/apiproxy/policies/AssignMessage.AddBaseUrlHeader.xml, proxies/live/apiproxy/policies/AssignMessage.Remove.nhsd-correlation-id-header.xml, proxies/live/apiproxy/policies/AssignMessage.Remove.x-request-id-header.xml, proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddAccessTokenHeader.xml, proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddApplicationIdHeader.xml, proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddNhsNumberHeader.xml, proxies/live/apiproxy/policies/AssignMessage.SetFlagCustomHeaderXRequestId.xml, proxies/live/apiproxy/policies/AssignMessage.Swap.CorrelationHeader.xml, proxies/live/apiproxy/policies/AssignMessage.Swap.TransactionID.xml, proxies/live/apiproxy/policies/DecodeJWT.DecodeIdToken.xml, proxies/live/apiproxy/policies/javascript.SetNhsNumber.xml, proxies/live/apiproxy/resources/jsc/SetNhsNumber.js, proxies/live/apiproxy/targets/target.xml
=> [ERSSUP-61575]-[]-[Add base URL header]-[AP]

sandbox/src/mocks/retrieveServiceRequests/responses/ServiceRequestsWithAppointmentAndTask.json, specification/components/schemas/codings/TaskCategory.yaml
=> [ERSSUP-61847]-[]-[Update Task.code to use new CodeSystem]-[DMW]

sandbox/src/mocks/OperationOutcome.json, sandbox/src/mocks/retrieveServiceRequests/responses/NoServiceRequests.json, sandbox/src/mocks/retrieveServiceRequests/responses/ServiceRequestsWithAppointmentAndTask.json, specification/components/schemas/Appointment.yaml, specification/components/schemas/HealthcareService.yaml, specification/components/schemas/OperationOutcome.yaml, specification/components/schemas/PractitionerRole.yaml, specification/components/schemas/ServiceRequest.yaml, specification/components/schemas/ServiceRequestBundle.yaml, specification/components/schemas/Task.yaml, specification/components/schemas/codings/TaskCategory.yaml, specification/components/schemas/responses/BadRequest.yaml, specification/components/schemas/responses/Forbidden.yaml, specification/components/schemas/responses/GatewayTimeout.yaml, specification/components/schemas/responses/InternalServerError.yaml, specification/components/schemas/responses/SendNotAcceptable.yaml, specification/components/schemas/responses/Unauthorized.yaml, specification/components/schemas/responses/retrieveHealthcareService/404Response.yaml, specification/components/schemas/responses/retrieveServiceRequests/400Response.yaml, specification/components/schemas/responses/retrieveServiceRequests/403Response.yaml, specification/e-referrals-service-patient-care-api.yaml
=> [ERSSUP-61259]-[JW/ADO]-[OperationOutcome and FHIR/R4 path]-[AP]

Makefile, package.json, scripts/api-gateway-integration.py
=> [ERSSUP-61574]-[AP]-[Changes to modify OAS file for Api Gateway]-[MAUD]

.github/workflows/pr-lint.yaml
=> [ERSSUP-62079]-[ADO/JW]-[Fix the pr lint]-[AP]

README.md
=> [ERSSUP-61771]-[JW]-[Update README]-[AP]

manifest_template.yml, proxies/live/apiproxy/policies/Quota.General.xml, proxies/live/apiproxy/policies/Quota.Referrals.xml
=> [ERSSUP-62323]-[]-[Updated rate limiting policies]-[JW]

manifest_template.yml
=> [ERSSUP-62493]-[ADO]-[Update rate limits]-[AP]

package-lock.json, package.json
=> [ERSSUP-62801]-[]-[Remove newman dependencies]-[DMW]

package-lock.json, package.json
=> [ERSSUP-]-[]-[Upgrade apigee tool]-[DMW]

poetry.lock, pyproject.toml
=> [ERSSUP-63261]-[AP]-[Upgrade black and poetry.lock]-[DMW]

.github/dependabot.yml
=> [ERSSUP-63293]-[JW/AP]-[Enable dependabot config in APIM-PC Repo]-[DMW]

.github/workflows/combine-prs.yml
=> [ERSSUP-64897]-[]-[Workflow to combine dependabot PRs]-[DMW]

.github/workflows/combine-prs.yml
=> [ERSSUP-64897]-[]-[Add dev-deps]-[DMW]

specification/components/schemas/Task.yaml, specification/components/schemas/identifiers/UBRN.yaml, specification/components/schemas/queryParameters/Patient.yaml, specification/components/schemas/queryParameters/RevInclude.yaml, specification/components/schemas/responses/InternalServerError.yaml, specification/components/schemas/responses/TooManyRequests.yaml, specification/components/schemas/responses/Unauthorized.yaml, specification/components/schemas/responses/retrieveServiceRequests/200Response.yaml
=> [ERSSUP-65716]-[]-[OAS documentation bug fixes]-[DMW]

azure/azure-pr-pipeline.yml, proxies/live/apiproxy/policies/AssignMessage.SetEchoTarget.xml, proxies/live/apiproxy/policies/AssignMessage.SetEchoTruststore.xml, proxies/live/apiproxy/policies/AssignMessage.SetTruststore.xml, proxies/live/apiproxy/targets/target.xml, tests/api_tests.py, tests/integration/test_headers.py
=> [ERSSUP-63069]-[]-[Run tests on ft05]-[DMW]

poetry.lock, pyproject.toml
=> [ERSSUP-66333]-[]-[Upgrade apim-test-utils]-[DMW]

Makefile, macros/manifest_macros.yml, manifest_template.yml
=> [ERSSUP-66050]-[AO]-[Refactor manifest_template]-[DMW]

.github/CODEOWNERS
=> [ERSSUP-59513]-[]-[Create a protected branch]-[DMW]

.github/CODEOWNERS
=> [ERSSUP-59513]-[]-[CODEOWNERS File to restrict approval reviews]-[DMW]

tests/conftest.py
=> [ERSSUP-68377]-[]-[Fixed iss url]-[DMW]

scripts/populate_placeholders.py, specification/components/schemas/Appointment.yaml, specification/components/schemas/ServiceRequest.yaml, specification/components/schemas/ServiceRequestBundle.yaml
=> ERSSUP-67858 - Bug fixes for issues found in the RapiDoc OAS migration

package-lock.json, package.json, redocly.yaml, specification/components/schemas/HealthcareService.yaml, specification/components/schemas/PractitionerRole.yaml, specification/e-referrals-service-patient-care-api.yaml
=> [ERSSUP-64283]-[]-[Replace speccy with redocly]-[DMW]

scripts/rhel_setup_environment.sh
=> [ERSSUP-69887]-[]-[Fix urllib compatibility on dev VM]-[DMW]

Makefile, scripts/ubuntu_clean_environment.sh, scripts/ubuntu_setup_environment.sh
=> [ERSSUP-70298]-[]-[Update APIM setup scripts to run against WSL]-[DMW]

pyproject.toml
=> [ERSSUP-70944]-[]-[Remove empty homepage from pyproject.toml]-[DMW]

Makefile, scripts/macos_clean_environment.sh, scripts/macos_setup_environment.sh
Also ensured git hooks were installed with execute permissions as part of make install target.
=> [ERSSUP-70290]-[]-[Added MacOS setup and cleanup scripts]-[JW]

azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, proxies/live/apiproxy/policies/Javascript.ValidateVectorOfTrust.xml, proxies/live/apiproxy/policies/RaiseFault.UnsupportedVectorOfTrust.xml, proxies/live/apiproxy/resources/jsc/ValidateVectorOfTrust.js, proxies/live/apiproxy/targets/target.xml, tests/conftest.py, tests/integration/test_headers.py, tests/integration/test_user_authentication.py, tests/utils.py
=> [ERSSUP-79819]-[]-[Added new test_user_authentication.py test]-[JW]

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, manifest_template.yml
=> [ERSSUP-79592]-[]-[Remove references to alpha environment]-[AP]
